; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i64 @add_select(i1 %cond, i64 %x, i64 %y) {
; CHECK-LABEL: @add_select(
; CHECK-NEXT:    [[ADD:%.*]] = select i1 [[COND:%.*]], i64 [[Y:%.*]], i64 0
; CHECK-NEXT:    [[RET:%.*]] = add i64 [[ADD]], [[X:%.*]]
; CHECK-NEXT:    ret i64 [[RET]]
;
  %add = add i64 %x, %y
  %ret = select i1 %cond, i64 %add, i64 %x, !unpredictable !0
  ret i64 %ret
}

!0 = !{}
